import Head from 'next/head';
import Characters from '../components/Characters';
import Header from '../components/Header';

export default function Home({ data }) {
  console.log(data);

  return (
    <div className=" bg-hero-pattern min-h-screen text-white">
      <Head>
        <title>Game of thrones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Characters data={data} />
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetch('https://thronesapi.com/api/v2/Characters').then((res) => res.json());

  return {
    props: {
      data,
    },
  };
}
